name: Lint Build Test Gradle project

on:
  workflow_dispatch:
  push:

jobs:
  lint-build-test-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Lint with ktLint
        run: ./gradlew ktlintCheck
      - name: Build with Gradle
        run: ./gradlew build
