name: Package main Gradle project

on:
  workflow_dispatch:

jobs:
  lint-build-test-package-gradle-project:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Mac OS runner only 64 bits. ARM target is common now but can't produce easily deployables yet...
        # Suggestion: add 'macOS-latest' when easy to add!
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Lint with ktLint
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: ktlintCheck
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: Test with Kotlin Test
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: allTests
      - name: Package Release Distribution For Current OS
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: packageReleaseDistributionForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: made-confirm-launch-dist-${{ runner.os }}
          path: ${{ github.workspace }}/composeApp/build/compose/binaries/
      - name: packageReleaseUberJarForCurrentOS
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: packageReleaseUberJarForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: made-confirm-launch-jar-${{ runner.os }}
          path: ${{ github.workspace }}/composeApp/build/compose/jars/
